all: pipe2
pipe_1:pipe__1.c
	gcc $^ -o $@
f_read:f_read.c
	gcc $^ -o $@
f_write:f_write.c
	gcc $^ -o $@
fifo_read:fifo_read.c
	gcc $^ -o $@
fifo_write:fifo_write.c
	gcc $^ -o $@
pipe2:pipe2.c
	gcc $^ -o $@
pipe:pipe.c
	gcc $^ -o $@

